// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SalesDashboard.Api.Data;

#nullable disable

namespace SalesDashboard.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260923171646_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SalesDashboard.Api.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ноутбуки"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Смартфоны"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Аксессуары"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Периферия"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Мониторы"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Сетевое оборудование"
                        });
                });

            modelBuilder.Entity("SalesDashboard.Api.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "АО Вектор #1",
                            Name = "Контакт 1",
                            Segment = "Mid-Market"
                        },
                        new
                        {
                            Id = 2,
                            Company = "ИП Сидоров #2",
                            Name = "Контакт 2",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 3,
                            Company = "ООО ТехноМир #3",
                            Name = "Контакт 3",
                            Segment = "Mid-Market"
                        },
                        new
                        {
                            Id = 4,
                            Company = "АО Прогресс #4",
                            Name = "Контакт 4",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 5,
                            Company = "ООО Альфа #5",
                            Name = "Контакт 5",
                            Segment = "Mid-Market"
                        },
                        new
                        {
                            Id = 6,
                            Company = "ООО Бета #6",
                            Name = "Контакт 6",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 7,
                            Company = "ЗАО Гамма #7",
                            Name = "Контакт 7",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 8,
                            Company = "ООО Дельта #8",
                            Name = "Контакт 8",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 9,
                            Company = "АО Эпсилон #9",
                            Name = "Контакт 9",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 10,
                            Company = "ООО Ромашка #10",
                            Name = "Контакт 10",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 11,
                            Company = "АО Вектор #11",
                            Name = "Контакт 11",
                            Segment = "Mid-Market"
                        },
                        new
                        {
                            Id = 12,
                            Company = "ИП Сидоров #12",
                            Name = "Контакт 12",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 13,
                            Company = "ООО ТехноМир #13",
                            Name = "Контакт 13",
                            Segment = "Mid-Market"
                        },
                        new
                        {
                            Id = 14,
                            Company = "АО Прогресс #14",
                            Name = "Контакт 14",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 15,
                            Company = "ООО Альфа #15",
                            Name = "Контакт 15",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 16,
                            Company = "ООО Бета #16",
                            Name = "Контакт 16",
                            Segment = "Mid-Market"
                        },
                        new
                        {
                            Id = 17,
                            Company = "ЗАО Гамма #17",
                            Name = "Контакт 17",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 18,
                            Company = "ООО Дельта #18",
                            Name = "Контакт 18",
                            Segment = "Mid-Market"
                        },
                        new
                        {
                            Id = 19,
                            Company = "АО Эпсилон #19",
                            Name = "Контакт 19",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 20,
                            Company = "ООО Ромашка #20",
                            Name = "Контакт 20",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 21,
                            Company = "АО Вектор #21",
                            Name = "Контакт 21",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 22,
                            Company = "ИП Сидоров #22",
                            Name = "Контакт 22",
                            Segment = "Mid-Market"
                        },
                        new
                        {
                            Id = 23,
                            Company = "ООО ТехноМир #23",
                            Name = "Контакт 23",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 24,
                            Company = "АО Прогресс #24",
                            Name = "Контакт 24",
                            Segment = "Mid-Market"
                        },
                        new
                        {
                            Id = 25,
                            Company = "ООО Альфа #25",
                            Name = "Контакт 25",
                            Segment = "Mid-Market"
                        },
                        new
                        {
                            Id = 26,
                            Company = "ООО Бета #26",
                            Name = "Контакт 26",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 27,
                            Company = "ЗАО Гамма #27",
                            Name = "Контакт 27",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 28,
                            Company = "ООО Дельта #28",
                            Name = "Контакт 28",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 29,
                            Company = "АО Эпсилон #29",
                            Name = "Контакт 29",
                            Segment = "Mid-Market"
                        },
                        new
                        {
                            Id = 30,
                            Company = "ООО Ромашка #30",
                            Name = "Контакт 30",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 31,
                            Company = "АО Вектор #31",
                            Name = "Контакт 31",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 32,
                            Company = "ИП Сидоров #32",
                            Name = "Контакт 32",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 33,
                            Company = "ООО ТехноМир #33",
                            Name = "Контакт 33",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 34,
                            Company = "АО Прогресс #34",
                            Name = "Контакт 34",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 35,
                            Company = "ООО Альфа #35",
                            Name = "Контакт 35",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 36,
                            Company = "ООО Бета #36",
                            Name = "Контакт 36",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 37,
                            Company = "ЗАО Гамма #37",
                            Name = "Контакт 37",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 38,
                            Company = "ООО Дельта #38",
                            Name = "Контакт 38",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 39,
                            Company = "АО Эпсилон #39",
                            Name = "Контакт 39",
                            Segment = "Mid-Market"
                        },
                        new
                        {
                            Id = 40,
                            Company = "ООО Ромашка #40",
                            Name = "Контакт 40",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 41,
                            Company = "АО Вектор #41",
                            Name = "Контакт 41",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 42,
                            Company = "ИП Сидоров #42",
                            Name = "Контакт 42",
                            Segment = "Mid-Market"
                        },
                        new
                        {
                            Id = 43,
                            Company = "ООО ТехноМир #43",
                            Name = "Контакт 43",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 44,
                            Company = "АО Прогресс #44",
                            Name = "Контакт 44",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 45,
                            Company = "ООО Альфа #45",
                            Name = "Контакт 45",
                            Segment = "Mid-Market"
                        },
                        new
                        {
                            Id = 46,
                            Company = "ООО Бета #46",
                            Name = "Контакт 46",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 47,
                            Company = "ЗАО Гамма #47",
                            Name = "Контакт 47",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 48,
                            Company = "ООО Дельта #48",
                            Name = "Контакт 48",
                            Segment = "Mid-Market"
                        },
                        new
                        {
                            Id = 49,
                            Company = "АО Эпсилон #49",
                            Name = "Контакт 49",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 50,
                            Company = "ООО Ромашка #50",
                            Name = "Контакт 50",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 51,
                            Company = "АО Вектор #51",
                            Name = "Контакт 51",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 52,
                            Company = "ИП Сидоров #52",
                            Name = "Контакт 52",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 53,
                            Company = "ООО ТехноМир #53",
                            Name = "Контакт 53",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 54,
                            Company = "АО Прогресс #54",
                            Name = "Контакт 54",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 55,
                            Company = "ООО Альфа #55",
                            Name = "Контакт 55",
                            Segment = "Mid-Market"
                        },
                        new
                        {
                            Id = 56,
                            Company = "ООО Бета #56",
                            Name = "Контакт 56",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 57,
                            Company = "ЗАО Гамма #57",
                            Name = "Контакт 57",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 58,
                            Company = "ООО Дельта #58",
                            Name = "Контакт 58",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 59,
                            Company = "АО Эпсилон #59",
                            Name = "Контакт 59",
                            Segment = "Mid-Market"
                        },
                        new
                        {
                            Id = 60,
                            Company = "ООО Ромашка #60",
                            Name = "Контакт 60",
                            Segment = "Mid-Market"
                        },
                        new
                        {
                            Id = 61,
                            Company = "АО Вектор #61",
                            Name = "Контакт 61",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 62,
                            Company = "ИП Сидоров #62",
                            Name = "Контакт 62",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 63,
                            Company = "ООО ТехноМир #63",
                            Name = "Контакт 63",
                            Segment = "Mid-Market"
                        },
                        new
                        {
                            Id = 64,
                            Company = "АО Прогресс #64",
                            Name = "Контакт 64",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 65,
                            Company = "ООО Альфа #65",
                            Name = "Контакт 65",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 66,
                            Company = "ООО Бета #66",
                            Name = "Контакт 66",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 67,
                            Company = "ЗАО Гамма #67",
                            Name = "Контакт 67",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 68,
                            Company = "ООО Дельта #68",
                            Name = "Контакт 68",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 69,
                            Company = "АО Эпсилон #69",
                            Name = "Контакт 69",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 70,
                            Company = "ООО Ромашка #70",
                            Name = "Контакт 70",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 71,
                            Company = "АО Вектор #71",
                            Name = "Контакт 71",
                            Segment = "Mid-Market"
                        },
                        new
                        {
                            Id = 72,
                            Company = "ИП Сидоров #72",
                            Name = "Контакт 72",
                            Segment = "Mid-Market"
                        },
                        new
                        {
                            Id = 73,
                            Company = "ООО ТехноМир #73",
                            Name = "Контакт 73",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 74,
                            Company = "АО Прогресс #74",
                            Name = "Контакт 74",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 75,
                            Company = "ООО Альфа #75",
                            Name = "Контакт 75",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 76,
                            Company = "ООО Бета #76",
                            Name = "Контакт 76",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 77,
                            Company = "ЗАО Гамма #77",
                            Name = "Контакт 77",
                            Segment = "Mid-Market"
                        },
                        new
                        {
                            Id = 78,
                            Company = "ООО Дельта #78",
                            Name = "Контакт 78",
                            Segment = "SMB"
                        },
                        new
                        {
                            Id = 79,
                            Company = "АО Эпсилон #79",
                            Name = "Контакт 79",
                            Segment = "Enterprise"
                        },
                        new
                        {
                            Id = 80,
                            Company = "ООО Ромашка #80",
                            Name = "Контакт 80",
                            Segment = "Mid-Market"
                        });
                });

            modelBuilder.Entity("SalesDashboard.Api.Entities.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarColor")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarColor = "#6366f1",
                            FullName = "Иван Петров",
                            IsActive = false,
                            Position = "Junior Sales",
                            Team = "Alpha"
                        },
                        new
                        {
                            Id = 2,
                            AvatarColor = "#0ea5e9",
                            FullName = "Мария Смирнова",
                            IsActive = true,
                            Position = "Junior Sales",
                            Team = "Bravo"
                        },
                        new
                        {
                            Id = 3,
                            AvatarColor = "#10b981",
                            FullName = "Алексей Кузнецов",
                            IsActive = true,
                            Position = "Sales Manager",
                            Team = "Charlie"
                        },
                        new
                        {
                            Id = 4,
                            AvatarColor = "#f59e0b",
                            FullName = "Ольга Попова",
                            IsActive = true,
                            Position = "Team Lead",
                            Team = "Delta"
                        },
                        new
                        {
                            Id = 5,
                            AvatarColor = "#ef4444",
                            FullName = "Дмитрий Соколов",
                            IsActive = true,
                            Position = "Senior Sales",
                            Team = "Alpha"
                        },
                        new
                        {
                            Id = 6,
                            AvatarColor = "#8b5cf6",
                            FullName = "Екатерина Лебедева",
                            IsActive = true,
                            Position = "Sales Manager",
                            Team = "Bravo"
                        },
                        new
                        {
                            Id = 7,
                            AvatarColor = "#6366f1",
                            FullName = "Сергей Новиков",
                            IsActive = true,
                            Position = "Sales Manager",
                            Team = "Charlie"
                        },
                        new
                        {
                            Id = 8,
                            AvatarColor = "#0ea5e9",
                            FullName = "Анна Морозова",
                            IsActive = true,
                            Position = "Team Lead",
                            Team = "Delta"
                        },
                        new
                        {
                            Id = 9,
                            AvatarColor = "#10b981",
                            FullName = "Павел Волков",
                            IsActive = true,
                            Position = "Junior Sales",
                            Team = "Alpha"
                        },
                        new
                        {
                            Id = 10,
                            AvatarColor = "#f59e0b",
                            FullName = "Юлия Зайцева",
                            IsActive = true,
                            Position = "Senior Sales",
                            Team = "Bravo"
                        },
                        new
                        {
                            Id = 11,
                            AvatarColor = "#ef4444",
                            FullName = "Артём Егоров",
                            IsActive = false,
                            Position = "Junior Sales",
                            Team = "Charlie"
                        },
                        new
                        {
                            Id = 12,
                            AvatarColor = "#8b5cf6",
                            FullName = "Наталья Павлова",
                            IsActive = true,
                            Position = "Junior Sales",
                            Team = "Delta"
                        },
                        new
                        {
                            Id = 13,
                            AvatarColor = "#6366f1",
                            FullName = "Роман Козлов",
                            IsActive = true,
                            Position = "Sales Manager",
                            Team = "Alpha"
                        },
                        new
                        {
                            Id = 14,
                            AvatarColor = "#0ea5e9",
                            FullName = "Виктория Степанова",
                            IsActive = true,
                            Position = "Team Lead",
                            Team = "Bravo"
                        },
                        new
                        {
                            Id = 15,
                            AvatarColor = "#10b981",
                            FullName = "Михаил Николаев",
                            IsActive = true,
                            Position = "Senior Sales",
                            Team = "Charlie"
                        },
                        new
                        {
                            Id = 16,
                            AvatarColor = "#f59e0b",
                            FullName = "Татьяна Орлова",
                            IsActive = true,
                            Position = "Senior Sales",
                            Team = "Delta"
                        },
                        new
                        {
                            Id = 17,
                            AvatarColor = "#ef4444",
                            FullName = "Игорь Фёдоров",
                            IsActive = true,
                            Position = "Sales Manager",
                            Team = "Alpha"
                        },
                        new
                        {
                            Id = 18,
                            AvatarColor = "#8b5cf6",
                            FullName = "Светлана Михайлова",
                            IsActive = true,
                            Position = "Senior Sales",
                            Team = "Bravo"
                        },
                        new
                        {
                            Id = 19,
                            AvatarColor = "#6366f1",
                            FullName = "Никита Беляев",
                            IsActive = true,
                            Position = "Senior Sales",
                            Team = "Charlie"
                        },
                        new
                        {
                            Id = 20,
                            AvatarColor = "#0ea5e9",
                            FullName = "Елена Виноградова",
                            IsActive = true,
                            Position = "Senior Sales",
                            Team = "Delta"
                        });
                });

            modelBuilder.Entity("SalesDashboard.Api.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseCost = 584.49m,
                            BasePrice = 750.80m,
                            CategoryId = 1,
                            Name = "Ноутбуки модель 1"
                        },
                        new
                        {
                            Id = 2,
                            BaseCost = 150.41m,
                            BasePrice = 227.67m,
                            CategoryId = 1,
                            Name = "Ноутбуки модель 2"
                        },
                        new
                        {
                            Id = 3,
                            BaseCost = 184.75m,
                            BasePrice = 250.81m,
                            CategoryId = 1,
                            Name = "Ноутбуки модель 3"
                        },
                        new
                        {
                            Id = 4,
                            BaseCost = 629.53m,
                            BasePrice = 949.18m,
                            CategoryId = 1,
                            Name = "Ноутбуки модель 4"
                        },
                        new
                        {
                            Id = 5,
                            BaseCost = 188.92m,
                            BasePrice = 312.99m,
                            CategoryId = 1,
                            Name = "Ноутбуки модель 5"
                        },
                        new
                        {
                            Id = 6,
                            BaseCost = 237.67m,
                            BasePrice = 321.90m,
                            CategoryId = 1,
                            Name = "Ноутбуки модель 6"
                        },
                        new
                        {
                            Id = 7,
                            BaseCost = 454.48m,
                            BasePrice = 632.70m,
                            CategoryId = 1,
                            Name = "Ноутбуки модель 7"
                        },
                        new
                        {
                            Id = 8,
                            BaseCost = 354.78m,
                            BasePrice = 481.13m,
                            CategoryId = 1,
                            Name = "Ноутбуки модель 8"
                        },
                        new
                        {
                            Id = 9,
                            BaseCost = 463.96m,
                            BasePrice = 566.58m,
                            CategoryId = 1,
                            Name = "Ноутбуки модель 9"
                        },
                        new
                        {
                            Id = 10,
                            BaseCost = 701.31m,
                            BasePrice = 1084.45m,
                            CategoryId = 1,
                            Name = "Ноутбуки модель 10"
                        },
                        new
                        {
                            Id = 11,
                            BaseCost = 367.98m,
                            BasePrice = 475.18m,
                            CategoryId = 2,
                            Name = "Смартфоны модель 1"
                        },
                        new
                        {
                            Id = 12,
                            BaseCost = 122.09m,
                            BasePrice = 198.16m,
                            CategoryId = 2,
                            Name = "Смартфоны модель 2"
                        },
                        new
                        {
                            Id = 13,
                            BaseCost = 702.95m,
                            BasePrice = 1071.28m,
                            CategoryId = 2,
                            Name = "Смартфоны модель 3"
                        },
                        new
                        {
                            Id = 14,
                            BaseCost = 85.32m,
                            BasePrice = 138.79m,
                            CategoryId = 2,
                            Name = "Смартфоны модель 4"
                        },
                        new
                        {
                            Id = 15,
                            BaseCost = 168.21m,
                            BasePrice = 293.31m,
                            CategoryId = 2,
                            Name = "Смартфоны модель 5"
                        },
                        new
                        {
                            Id = 16,
                            BaseCost = 604.07m,
                            BasePrice = 912.05m,
                            CategoryId = 2,
                            Name = "Смартфоны модель 6"
                        },
                        new
                        {
                            Id = 17,
                            BaseCost = 199.10m,
                            BasePrice = 243.88m,
                            CategoryId = 2,
                            Name = "Смартфоны модель 7"
                        },
                        new
                        {
                            Id = 18,
                            BaseCost = 296.56m,
                            BasePrice = 459.64m,
                            CategoryId = 2,
                            Name = "Смартфоны модель 8"
                        },
                        new
                        {
                            Id = 19,
                            BaseCost = 706.85m,
                            BasePrice = 849.90m,
                            CategoryId = 2,
                            Name = "Смартфоны модель 9"
                        },
                        new
                        {
                            Id = 20,
                            BaseCost = 478.58m,
                            BasePrice = 805.50m,
                            CategoryId = 2,
                            Name = "Смартфоны модель 10"
                        },
                        new
                        {
                            Id = 21,
                            BaseCost = 648.69m,
                            BasePrice = 928.11m,
                            CategoryId = 3,
                            Name = "Аксессуары модель 1"
                        },
                        new
                        {
                            Id = 22,
                            BaseCost = 169.30m,
                            BasePrice = 205.84m,
                            CategoryId = 3,
                            Name = "Аксессуары модель 2"
                        },
                        new
                        {
                            Id = 23,
                            BaseCost = 90.81m,
                            BasePrice = 151.56m,
                            CategoryId = 3,
                            Name = "Аксессуары модель 3"
                        },
                        new
                        {
                            Id = 24,
                            BaseCost = 551.17m,
                            BasePrice = 699.49m,
                            CategoryId = 3,
                            Name = "Аксессуары модель 4"
                        },
                        new
                        {
                            Id = 25,
                            BaseCost = 249.97m,
                            BasePrice = 415.81m,
                            CategoryId = 3,
                            Name = "Аксессуары модель 5"
                        },
                        new
                        {
                            Id = 26,
                            BaseCost = 281.69m,
                            BasePrice = 447.57m,
                            CategoryId = 3,
                            Name = "Аксессуары модель 6"
                        },
                        new
                        {
                            Id = 27,
                            BaseCost = 164.92m,
                            BasePrice = 202.31m,
                            CategoryId = 3,
                            Name = "Аксессуары модель 7"
                        },
                        new
                        {
                            Id = 28,
                            BaseCost = 533.65m,
                            BasePrice = 805.57m,
                            CategoryId = 3,
                            Name = "Аксессуары модель 8"
                        },
                        new
                        {
                            Id = 29,
                            BaseCost = 90.64m,
                            BasePrice = 131.63m,
                            CategoryId = 3,
                            Name = "Аксессуары модель 9"
                        },
                        new
                        {
                            Id = 30,
                            BaseCost = 615.27m,
                            BasePrice = 970.33m,
                            CategoryId = 3,
                            Name = "Аксессуары модель 10"
                        },
                        new
                        {
                            Id = 31,
                            BaseCost = 224.76m,
                            BasePrice = 271.50m,
                            CategoryId = 4,
                            Name = "Периферия модель 1"
                        },
                        new
                        {
                            Id = 32,
                            BaseCost = 342.13m,
                            BasePrice = 465.46m,
                            CategoryId = 4,
                            Name = "Периферия модель 2"
                        },
                        new
                        {
                            Id = 33,
                            BaseCost = 104.93m,
                            BasePrice = 171.13m,
                            CategoryId = 4,
                            Name = "Периферия модель 3"
                        },
                        new
                        {
                            Id = 34,
                            BaseCost = 106.75m,
                            BasePrice = 157.83m,
                            CategoryId = 4,
                            Name = "Периферия модель 4"
                        },
                        new
                        {
                            Id = 35,
                            BaseCost = 59.63m,
                            BasePrice = 100.10m,
                            CategoryId = 4,
                            Name = "Периферия модель 5"
                        },
                        new
                        {
                            Id = 36,
                            BaseCost = 401.34m,
                            BasePrice = 605.26m,
                            CategoryId = 4,
                            Name = "Периферия модель 6"
                        },
                        new
                        {
                            Id = 37,
                            BaseCost = 449.68m,
                            BasePrice = 542.03m,
                            CategoryId = 4,
                            Name = "Периферия модель 7"
                        },
                        new
                        {
                            Id = 38,
                            BaseCost = 713.07m,
                            BasePrice = 861.20m,
                            CategoryId = 4,
                            Name = "Периферия модель 8"
                        },
                        new
                        {
                            Id = 39,
                            BaseCost = 52.46m,
                            BasePrice = 64.96m,
                            CategoryId = 4,
                            Name = "Периферия модель 9"
                        },
                        new
                        {
                            Id = 40,
                            BaseCost = 573.31m,
                            BasePrice = 699.85m,
                            CategoryId = 4,
                            Name = "Периферия модель 10"
                        },
                        new
                        {
                            Id = 41,
                            BaseCost = 780.81m,
                            BasePrice = 1372.18m,
                            CategoryId = 5,
                            Name = "Мониторы модель 1"
                        },
                        new
                        {
                            Id = 42,
                            BaseCost = 418.96m,
                            BasePrice = 597.10m,
                            CategoryId = 5,
                            Name = "Мониторы модель 2"
                        },
                        new
                        {
                            Id = 43,
                            BaseCost = 543.28m,
                            BasePrice = 666.42m,
                            CategoryId = 5,
                            Name = "Мониторы модель 3"
                        },
                        new
                        {
                            Id = 44,
                            BaseCost = 348.21m,
                            BasePrice = 447.49m,
                            CategoryId = 5,
                            Name = "Мониторы модель 4"
                        },
                        new
                        {
                            Id = 45,
                            BaseCost = 399.56m,
                            BasePrice = 669.41m,
                            CategoryId = 5,
                            Name = "Мониторы модель 5"
                        },
                        new
                        {
                            Id = 46,
                            BaseCost = 475.89m,
                            BasePrice = 685.48m,
                            CategoryId = 5,
                            Name = "Мониторы модель 6"
                        },
                        new
                        {
                            Id = 47,
                            BaseCost = 287.90m,
                            BasePrice = 502.20m,
                            CategoryId = 5,
                            Name = "Мониторы модель 7"
                        },
                        new
                        {
                            Id = 48,
                            BaseCost = 519.39m,
                            BasePrice = 852.35m,
                            CategoryId = 5,
                            Name = "Мониторы модель 8"
                        },
                        new
                        {
                            Id = 49,
                            BaseCost = 65.53m,
                            BasePrice = 113.30m,
                            CategoryId = 5,
                            Name = "Мониторы модель 9"
                        },
                        new
                        {
                            Id = 50,
                            BaseCost = 816.14m,
                            BasePrice = 1142.35m,
                            CategoryId = 5,
                            Name = "Мониторы модель 10"
                        },
                        new
                        {
                            Id = 51,
                            BaseCost = 618.56m,
                            BasePrice = 802.53m,
                            CategoryId = 6,
                            Name = "Сетевое оборудование модель 1"
                        },
                        new
                        {
                            Id = 52,
                            BaseCost = 132.51m,
                            BasePrice = 194.96m,
                            CategoryId = 6,
                            Name = "Сетевое оборудование модель 2"
                        },
                        new
                        {
                            Id = 53,
                            BaseCost = 316.60m,
                            BasePrice = 527.35m,
                            CategoryId = 6,
                            Name = "Сетевое оборудование модель 3"
                        },
                        new
                        {
                            Id = 54,
                            BaseCost = 168.84m,
                            BasePrice = 216.25m,
                            CategoryId = 6,
                            Name = "Сетевое оборудование модель 4"
                        },
                        new
                        {
                            Id = 55,
                            BaseCost = 222.53m,
                            BasePrice = 346.03m,
                            CategoryId = 6,
                            Name = "Сетевое оборудование модель 5"
                        },
                        new
                        {
                            Id = 56,
                            BaseCost = 460.27m,
                            BasePrice = 824.90m,
                            CategoryId = 6,
                            Name = "Сетевое оборудование модель 6"
                        },
                        new
                        {
                            Id = 57,
                            BaseCost = 662.98m,
                            BasePrice = 1062.91m,
                            CategoryId = 6,
                            Name = "Сетевое оборудование модель 7"
                        },
                        new
                        {
                            Id = 58,
                            BaseCost = 621.96m,
                            BasePrice = 854.38m,
                            CategoryId = 6,
                            Name = "Сетевое оборудование модель 8"
                        },
                        new
                        {
                            Id = 59,
                            BaseCost = 491.65m,
                            BasePrice = 881.97m,
                            CategoryId = 6,
                            Name = "Сетевое оборудование модель 9"
                        },
                        new
                        {
                            Id = 60,
                            BaseCost = 570.67m,
                            BasePrice = 693.10m,
                            CategoryId = 6,
                            Name = "Сетевое оборудование модель 10"
                        });
                });

            modelBuilder.Entity("SalesDashboard.Api.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Date");

                    b.HasIndex("ManagerId");

                    b.HasIndex("Status", "Date");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("SalesDashboard.Api.Entities.SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("SaleId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("SalesDashboard.Api.Entities.Product", b =>
                {
                    b.HasOne("SalesDashboard.Api.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SalesDashboard.Api.Entities.Sale", b =>
                {
                    b.HasOne("SalesDashboard.Api.Entities.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesDashboard.Api.Entities.Manager", "Manager")
                        .WithMany("Sales")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("SalesDashboard.Api.Entities.SaleItem", b =>
                {
                    b.HasOne("SalesDashboard.Api.Entities.Product", "Product")
                        .WithMany("SaleItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesDashboard.Api.Entities.Sale", "Sale")
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("SalesDashboard.Api.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SalesDashboard.Api.Entities.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("SalesDashboard.Api.Entities.Manager", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("SalesDashboard.Api.Entities.Product", b =>
                {
                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("SalesDashboard.Api.Entities.Sale", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
